name: Node CI

on:
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 12 * * *'
jobs:
  build:

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, macOS-latest, ubuntu-latest]
    runs-on:  ubuntu-latest


    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
 
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Say hello
      run: echo Hello, $USER!
      env:
        USER: "cttest"
    - name: Say hello to ${{secrets.USER}}
      run: |
        echo Hello, ${{secrets.USER}}
        echo Let\'s try Actions

